[package]
name = "notary"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

tlsn-utils = { git = "https://github.com/tlsnotary/tlsn-utils", rev = "45370cc" }
tlsn-utils-aio = { git = "https://github.com/tlsnotary/tlsn-utils", rev = "45370cc" }
tlsn-core = { git = "https://github.com/tlsnotary/tlsn", rev = "3554db8" }
tlsn-common = { git = "https://github.com/tlsnotary/tlsn", rev = "3554db8" }
tlsn-prover = { git = "https://github.com/tlsnotary/tlsn", rev = "3554db8" }
tlsn-verifier = { git = "https://github.com/tlsnotary/tlsn", rev = "3554db8" }
tlsn-server-fixture = { git = "https://github.com/tlsnotary/tlsn", rev = "3554db8" }
tlsn-formats = { git = "https://github.com/tlsnotary/tlsn", rev = "3554db8" }

tracing = "0.1"
tracing-subscriber = "0.3"

futures = "0.3"
http-body-util = "0.1"
hyper = { version = "1.1", features = ["client", "http1", "server"] }
hyper-util = { version = "0.1", features = ["full"] }

elliptic-curve = { version = "0.13.5", features = ["pkcs8"] }
signature = "2"
p256 = "0.13"

[[ai]]
name = "ai"
path = "main2.rs"